### ISSUE TITLE
Dry run should indicate it is a dry run

### ISSUE THREAD

**Issue by ipkpjersi** [ludviglundgren/qbittorrent-cli#49]
To me, it seems like the only way to tell if you are doing a dry run vs an actual run is just examining the amount of time it takes. I think there should be some kind of indication that it is indeed a dry run

For example:

Dry run: `Import finished in: 306.529729ms`

Actual run: `Import finished in: 1.368155058s`

This program is fantastic btw, it worked great for me for migrating from rtorrent 0.9.8 to qbittorrent-nox 4.5.2

**Comment by ludviglundgren** [comment]
Hey! Can probably do something to make it more clear it does a dry run yes!

That's awesome it worked with qbit 4.5.2!

**Comment by ipkpjersi** [comment]
Yep it recognized all of the torrents in qbittorrent, it worked quite well! 

The only thing I noticed was that the torrents themselves were still pointing to the rtorrent folder not the qbittorrent folder, so it said "missing files" so then I had to right click them and "Set Location" on them, then it picked up the existing files right away and was able to start seeding them instantly.

**Comment by ludviglundgren** [comment]
Okay, then it might need some additional work to fix that! :smile:

**Comment by ipkpjersi** [comment]
That looks much better, thanks a bunch!

The only thing I would suggest is kind of nit picky but maybe on line 109, modify it so it *also* indicates that it's a dry-run, that way users don't think that it actually has imported all of the files when it says it has: https://github.com/ludviglundgren/qbittorrent-cli/blob/26986d96e6c652e97c02e6c61ac7f94c84ad30d7/cmd/import.go#LL109C49-L109C49

**Comment by ludviglundgren** [comment]
I'll fix in another PR :smile: 

I have barely touched the import code since it was initially built, and it has worked fine but seeing lots of room for improvement. It basically does everything except writing the files, so reads all even on dry run. That should be fixed as well.

Gonna do some other things to improve the tool and will probably make a new v2 version with broken backwards compatibility. In the end it will be a better tool!
